### ISSUE TITLE
Updates for CSI 0.1

### ISSUE THREAD

**Issue by codenrhoden** [rexray/csi-nfs#7]

**Comment by deric** [comment]
After going through the instructions in the README I'm getting:
```
$ csc gets
0.0.0
```
So `0.1.0` is not supported yet?

**Comment by codenrhoden** [comment]
There is no formal tag of `0.1.0` for CSI yet. So it doesn't exist.

**Comment by deric** [comment]
Right, makes sense. At this point it just makes harder to test it. Hopefully the `0.1.0` will be tagged soon.

**Comment by codenrhoden** [comment]
Yeah, I get it. It is annoying to add the `-version 0.0.0` flag to the `csc` commands. I just didn't want there to be plugins out in the wile that advertised `0.1.0` support when I know that what the plugin looks like today, and what it will actually look like when `0.1.0` is tagged will be very different.

This is issue is to capture the work that will be required once `0.1.0` is tagged. We had originally expected that tag to happen late October, but now I'm more hoping "in the next few weeks". I really don't know.
